[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

; Cấu hình PSRAM OPI cho ESP32-S3-WROOM-1 (Freenove)
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 8MB
upload_port = COM10
monitor_port = COM10

build_flags = 
    -DBOARD_HAS_PSRAM

lib_deps = 
    adafruit/Adafruit SSD1306 @ ^2.5.9
    adafruit/Adafruit GFX Library @ ^1.11.9
    claws/BH1750 @ ^1.3.0
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    z3t0/IRremote @ ^4.4.1
    bblanchon/ArduinoJson @ ^7.0.4
    madhephaestus/ESP32Servo @ ^3.0.5
    knolleary/PubSubClient @ ^2.8