/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 02.10.2026 14:33:18

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 8
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 3840;
#else
constexpr int kTensorArenaSize = 2816;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,975 } };
const TfArray<1, float> quant0_scale = { 1, { 0.052205193787813187, } };
const TfArray<1, int> quant0_zero = { 1, { 15 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 75, 13, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 75, 1, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 38, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data4[4] = { 1, 38, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data5[2] = { -1, 304, };
const TfArray<1, int> tensor_dimension5 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data6[11] = { -59, -275, -424, 313, -130, -431, 897, 74, -37, -232, 243, };
const TfArray<1, int> tensor_dimension6 = { 1, { 11 } };
const TfArray<1, float> quant6_scale = { 1, { 0.00033972566598095, } };
const TfArray<1, int> quant6_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data7[11*304] = { 
  21, 16, -55, 39, -35, -49, -21, 23, -18, -17, -6, -8, -2, -30, -1, -35, 25, 53, -7, 38, -79, -67, 11, 20, 24, -27, 0, 28, -2, -44, 23, 7, 38, 39, -18, -15, -58, -28, 31, -9, 12, -16, 45, 8, 44, -2, 30, 22, 29, 43, 20, 23, -53, 3, 9, 10, 3, -39, 17, 17, -1, -1, 6, 23, 8, 22, -9, 9, 9, -4, -7, -6, -25, 1, 27, 3, 13, 13, -12, 11, -36, 23, 20, 5, -47, -15, -9, -11, -33, -19, 35, 14, -24, 23, -14, 30, -7, 19, -24, 5, -1, 3, -26, -7, -17, -20, 11, -44, 4, 10, -26, 27, -15, 17, -11, 8, -12, -17, 29, 15, -19, -28, 8, 30, -9, -15, 8, 9, 6, 25, 8, 15, -37, 22, 15, -5, 5, -38, -6, 29, 13, 28, -25, 21, 11, 9, -3, 2, -22, -2, 11, 5, -34, -3, 14, -7, 1, 34, -11, 6, 21, -3, -3, -8, 19, 2, 31, 14, 25, -12, -41, 34, 2, 32, -21, 8, 5, 13, 8, -10, -14, -34, 32, 0, 37, -19, -12, 11, 24, 15, -10, 14, 15, 1, -2, -19, -35, -50, 24, 12, 17, -45, -28, 16, 14, 23, 18, 23, 17, 4, -38, -31, -27, -6, -15, 23, -13, -65, -50, -20, -7, 40, 0, -27, 30, 21, -14, -35, -88, -24, 10, 18, -2, -46, 49, 3, 10, 19, 11, -67, -5, 4, -11, -53, -69, -40, 9, -9, 17, -37, 25, 20, 26, -22, 37, -35, 3, -30, -71, -46, -28, -7, -9, 8, 24, 11, 8, 32, 6, -16, -23, -122, 3, 9, -10, -1, -26, -38, -10, 25, 19, -17, -24, -1, 26, -8, -22, -11, 20, -50, 36, 2, -34, -41, 0, -19, 1, -35, 24, 6, 14, -8, 16, -8, 
  28, 14, 5, 30, -64, -21, 14, 27, -10, 12, 13, 22, 4, -26, -37, -15, 22, 42, 9, -9, -55, -65, -36, 9, -20, -37, 10, -3, -10, -93, -6, -19, 6, 31, -11, -5, -47, -45, -16, 12, 18, -12, 6, -6, 25, -42, 33, -23, 3, 36, 5, 13, -30, -8, 17, 9, 20, -50, 27, 19, 22, 20, 29, -13, 17, 39, -12, 2, -27, 14, -15, 27, -19, -60, 12, 10, -37, 16, 26, -24, 27, 28, 3, -6, -18, 5, -80, 19, 12, -68, 2, -1, -30, 8, 22, -40, 20, 35, -23, -4, 11, -20, -16, -10, 34, -31, -10, -12, -11, -14, 40, -48, 12, 4, -59, -8, 7, -21, 3, -4, 17, -11, 41, 5, 0, 15, 30, -54, 20, 15, -25, -23, 19, -12, 27, -15, 4, -11, 8, 48, 1, 35, 25, -46, 22, 16, -36, -32, 9, -1, 27, 8, -8, 18, -9, 5, 7, 7, 24, -57, 13, -62, -49, -38, 12, -8, 18, -20, -20, -24, 8, 30, 14, 1, 8, -61, 25, 27, -48, 13, 25, -8, 11, 17, -29, 25, -1, 17, -11, -10, 18, -86, 4, -3, 7, -35, 14, 32, 6, -10, 7, 11, 28, 24, -12, 22, 21, -50, 32, 31, -19, -24, 2, -13, -9, 13, 37, 17, 17, 24, -38, -12, 31, -54, 2, 19, 14, -32, -7, 4, -6, 11, -11, 1, 11, 18, 0, -16, 14, -76, 15, 12, 20, -2, -32, 7, -15, -5, 10, -15, 30, -2, -1, -53, -22, -51, 12, -12, -8, -57, 2, -31, 28, 3, 29, 12, 24, 28, 9, -68, -12, -30, 1, -13, 0, -8, -17, -2, -45, 0, -18, -20, 43, 18, 6, 26, -9, -61, -12, -4, 5, -2, -4, -14, 5, -4, 10, -46, 51, 22, -40, -93, -20, -10, 
  26, 27, -15, -42, 55, 0, -17, 34, -19, 28, -3, -2, -23, -9, 31, -67, 36, 3, -41, -1, 28, 14, -35, 42, -59, -7, 6, 7, -21, 20, 21, -69, 33, 41, -56, -39, 6, -37, -34, 22, -33, -29, 0, -11, -26, -10, 11, -48, 6, 24, -65, -48, 8, -15, -3, 0, -10, -16, -56, -5, 4, 21, 26, -109, 0, 51, -18, -14, -13, -9, -7, -17, -6, -27, -19, -9, 17, 5, 11, -25, 7, 21, 1, 21, -14, -15, -42, 5, 16, 1, -62, -33, -3, -17, -4, 17, -17, 1, -5, 28, 0, -38, -18, -31, -24, -43, -25, 11, -9, -3, 16, 4, -12, -8, -13, 22, -25, -18, -59, -35, -16, -27, -10, 6, -31, -6, 12, 8, -38, 25, 24, 31, -33, -58, -22, -29, -8, 5, 10, -26, -13, -42, -6, 17, -23, 2, 12, 34, -14, -58, -20, -34, -10, 20, -22, -16, -10, -20, -19, 4, -6, 11, 16, 25, -64, -40, -79, -16, 4, -11, -20, -40, -45, 0, -1, 9, -26, 2, 30, 33, -46, -66, -89, -15, 7, -28, -37, -78, -45, -71, -20, -1, -39, -11, 26, 25, -49, -45, -48, -31, 17, -10, -72, -64, -67, -78, -57, 24, -48, -43, 19, 25, -10, -51, -7, -37, 15, -12, -21, -67, -38, -36, -60, 22, 2, 17, 11, 21, 4, -25, -14, -5, 2, 3, -5, -19, 7, -12, -30, 0, -10, 3, 6, 35, 11, -25, 7, 14, 40, 2, -44, -6, -12, 22, -16, 27, -23, 24, 1, 33, 2, 8, -15, -4, 22, -1, -78, -53, -26, 41, 5, 21, -28, -21, 15, 9, -18, 1, -7, -1, 6, 4, -112, -55, -7, 28, -32, 3, -5, -5, -25, -49, -34, 11, -7, 2, -18, 19, -3, -40, 8, -11, -7, -33, 
  54, -24, -21, -19, 36, -21, -45, 58, -33, -61, 15, 7, 0, -51, 2, -51, 30, -3, 0, -27, 18, -20, -15, 43, -2, -53, -36, -6, -19, -60, -7, -7, 30, -52, -30, -9, -2, 3, -19, 5, 25, -29, -24, -18, -13, -35, 9, -12, 19, -38, 13, 6, 22, 9, -18, 2, 26, -51, -9, -38, -35, -28, -6, 24, 43, -10, 1, 5, 6, 8, 47, -3, 45, -7, -43, -29, -29, -27, -7, 13, 24, -47, -7, 4, 0, -11, 32, 4, 27, 20, -23, -42, -5, -7, 5, -5, -17, -5, 8, -5, -9, 13, 32, -12, 24, 13, -25, -35, 4, -4, 12, 30, 13, -28, -6, -5, -14, -22, 54, -13, 5, 15, -77, -30, -7, -16, 22, 13, 3, -36, -6, -11, -31, -31, 12, 17, -10, -36, -52, 7, 10, -12, 19, 2, 16, -29, -20, -5, -26, -35, 12, 4, 2, -38, -11, -10, 38, -25, 20, 0, 42, 19, 0, -26, -2, -26, -16, 2, -14, -38, -39, -37, 4, -12, -2, 8, 15, 14, -6, -21, -29, 5, 16, 36, -29, -32, -28, 6, 10, -9, -14, 4, 25, 29, -4, -14, -28, -16, 31, 7, -18, -32, -45, -6, 9, -76, -15, 5, -4, 13, 14, 19, 5, -18, 17, 11, -15, -44, -57, -19, 7, 0, -18, 24, 26, 26, -5, 14, -11, 11, 32, 21, 1, -20, -82, -7, -17, 21, 2, 35, 16, 26, -7, -20, -39, 25, 35, 35, -20, -1, -57, 9, 0, -35, 0, -21, 16, 21, -2, -19, -1, 4, -4, 22, -21, 2, -17, -14, -9, -17, 8, 2, 10, -17, -16, -28, 4, 0, -18, 11, -12, -59, -1, 0, -6, 3, -1, -19, 22, 9, -28, -12, 13, 15, -30, 14, 14, -41, -5, 11, -44, -6, 20, -42, 
  -38, -4, -6, 30, -25, 11, 47, -44, -4, 26, -34, 9, 3, -5, -32, -2, -23, -23, 15, 12, -10, -5, 55, -12, -19, 39, 10, 5, 43, 3, -19, -1, -11, -61, 14, 23, 4, -44, 32, -29, -8, 10, 4, 11, 7, 19, 6, 31, -47, -32, 30, -3, 3, -8, 20, -41, -56, 26, -9, -5, 17, 2, -37, 20, -32, -53, 12, 20, 3, -13, 10, -27, -22, 16, -33, -11, -2, -28, -53, 5, -42, -46, 28, 20, 24, -32, 19, -14, -10, 35, -38, 24, 7, -34, -42, 26, 5, -6, 7, 25, 5, -51, -5, -6, -33, 23, -14, 29, 14, -43, -69, -5, 0, -13, 19, 17, -10, -13, 3, -20, -22, 18, 6, -49, 20, -6, -54, -3, -51, -23, 28, 19, -28, -37, -5, -50, 19, -3, -15, -10, 24, -1, -41, 11, -29, -20, 6, 2, -36, 4, -18, -26, -18, -33, -30, -29, -19, 12, -26, 13, -34, -23, -6, 10, -6, -19, 4, -50, -16, -3, 2, -9, 1, -14, -32, 16, -30, -17, 13, 27, 17, -37, -9, -29, -16, 4, -49, -41, -1, -3, -18, 10, -12, -26, 9, 11, 2, -36, -8, -19, -21, -2, -36, -11, 10, -2, -16, 17, -49, -42, 3, 9, -14, 9, 0, -20, -26, 21, 43, -5, 32, 43, -16, 18, -33, -41, 0, 10, -10, -1, -2, -34, -34, 6, -8, 7, 18, 28, -21, 22, 0, -5, 23, 24, -7, -22, -16, -26, 5, -2, -29, -2, 20, 25, -24, 25, 6, -26, 12, 26, -19, -16, -7, -21, -15, 9, -14, -15, 4, -17, -22, 35, -10, -26, 32, 25, 0, -25, 15, -2, 15, 9, -39, -9, -17, 10, -9, 29, -11, -15, 12, 13, 6, -7, 37, 2, 2, 12, -28, 9, 10, -29, -37, 36, 
  22, 24, 28, -21, -22, -3, -39, 18, 12, -45, -30, -15, -27, -53, 60, -38, 45, 21, 20, 18, -32, 24, -75, 5, 37, -36, 40, -30, -5, -28, 54, -65, 11, 13, 23, 22, -42, 16, -29, -9, 25, -44, -9, 0, 7, -55, 26, -31, 24, 15, 25, 13, -111, 21, -21, 17, 44, -28, -24, -3, 0, -61, 25, 8, 26, 10, 7, 18, -78, 9, -64, -1, 32, -29, 5, 5, -15, -44, 27, 14, 2, -4, -3, 10, -78, 14, -17, 7, 26, -18, -25, 14, -13, -61, 36, 19, 2, 3, 2, 1, -69, 17, -37, 3, 51, -8, 40, -19, -6, -24, 27, 21, -14, 18, -5, -4, -39, -21, -20, 15, 43, 4, -55, -42, -54, -78, 27, 4, -24, -4, 16, -25, -25, -38, -6, 2, 52, 29, 23, -42, -1, -46, 21, -14, -27, -2, 4, -7, -26, -15, -42, 1, 45, 6, 35, -13, 0, -35, 20, 2, -40, -28, -8, -14, -11, 24, 4, -10, 13, -8, 27, -22, 5, -30, 18, 10, -38, -19, 6, -11, -4, 27, -6, -16, -1, 10, 17, -24, 5, -45, 1, 12, 12, 4, 2, -17, 9, -21, 22, 2, -40, 34, -18, -80, 17, -19, -11, 5, 4, 2, -8, 0, -17, -35, 22, 5, -51, 32, -28, -78, 20, -10, -6, 17, 9, -7, -13, -12, -4, -10, 15, -3, -77, -1, -39, -69, -13, 8, -23, 28, 27, -32, -17, -28, -4, 11, 40, 26, -42, 34, -32, -30, -2, 0, -39, 18, -2, 10, -21, 30, -72, 13, 9, 5, -47, 12, 22, -21, -18, 8, -44, -52, 36, 69, -5, -7, -17, -2, -19, 20, -45, -12, 1, -8, -8, -7, -46, -64, 18, -8, -39, -25, -25, 11, 6, 17, -55, -12, 4, 19, -2, 8, -46, -34, 
  -42, -17, 39, 10, 11, 2, -11, 20, 46, 49, -12, -46, 7, 13, -5, 52, -11, -17, -3, 2, 28, -5, 17, -27, 13, 15, -11, -4, 33, 9, 6, 5, 9, -19, 6, -7, -8, 10, -9, 30, -8, -19, -18, 11, 1, 29, -25, 16, 2, 4, -14, -2, 23, 19, 14, -2, -21, 21, -40, -24, -13, 6, -6, -4, -22, -34, -23, -44, 7, -6, 0, -8, 27, -17, -29, -29, -34, 27, -13, -31, -44, -34, -39, -39, -21, 20, 8, -21, -1, -18, -12, 9, -41, 35, -1, -33, -10, -6, -11, -68, 19, 24, 5, -19, -1, 2, -41, -19, 11, 2, 5, -26, -16, -40, -20, -42, 13, 22, 14, -7, -10, -19, 16, -22, -29, 43, 4, -2, -7, -13, 2, -20, 12, 25, -12, -7, -22, -16, 27, -11, -12, 26, -14, -29, 6, -27, -1, -1, 31, 19, 8, -3, 16, 15, 10, 12, 6, 22, -15, -12, 6, -18, -21, -44, 24, 22, -19, 12, 9, 7, 40, 7, -7, 8, -7, -6, -7, -24, -18, -45, 22, 22, -42, 4, 13, 21, 41, -15, 9, 5, 5, -25, 18, -8, 4, -25, 17, 25, -9, -11, 35, 9, 60, -11, -33, 60, 34, -10, -1, 18, -10, -37, 38, 25, -21, -5, 10, 2, 3, -8, 4, 10, 32, -17, -23, -24, 1, -20, 15, 6, 12, 18, 27, 5, 32, 2, 5, 35, 27, -4, 7, -9, -4, -31, 27, -10, -7, 28, 18, -16, 6, -9, 1, 68, 18, -1, -8, -38, 11, -33, 18, 2, 1, 10, 5, 23, -44, -25, 1, -1, 23, 32, -12, -38, 24, -56, -1, 10, -8, -23, 25, -23, -8, -20, -3, 20, 24, 20, 27, 18, 8, -45, -9, 21, 18, 23, 6, -2, -48, -30, 15, 17, 51, 48, 
  -40, -46, -40, -93, -7, 28, 39, -50, -1, -5, -14, 2, 18, 39, -47, -88, -49, -51, 11, -52, -11, 15, 14, -41, 24, 20, -23, 7, 9, 3, -25, 7, -24, -54, -3, 3, -7, -1, 39, -24, 19, -3, -44, 39, 11, -31, -58, 29, -6, -50, -87, -55, 18, -5, 36, 20, -54, 13, 6, 26, 26, 6, -58, 10, -44, 0, 18, 13, 12, -37, 5, 0, 11, 9, 40, -7, -4, -35, -24, 3, -26, 21, 30, 23, -7, -3, 27, 5, 29, -8, 28, 0, 28, 14, -33, 27, -41, 7, 4, 12, -8, 16, 51, 7, 0, 24, 0, 11, 34, 3, -65, 25, -3, 34, 24, 3, -8, -17, 8, 12, -25, 0, -6, -1, 43, -3, -7, 16, -3, 11, 23, 2, -19, -10, 17, 18, -7, -25, -19, -10, -38, 27, -8, 19, 8, 18, 7, -3, -37, 7, 23, 21, 25, -14, -34, 32, 4, -20, -21, 4, 0, 21, -9, -1, -83, -25, 5, 23, 5, -21, 3, 27, 19, -19, -15, 9, -11, -13, -11, -19, -43, 37, 4, -13, 5, -45, 17, 13, -11, -19, -18, -2, -22, 15, -41, -35, -23, -15, 19, -3, -44, -26, -6, 3, 12, -2, -57, -44, -10, 31, -10, -14, -41, -1, -11, 0, -1, -20, -39, 10, 24, -1, 9, -87, -33, -38, -30, -39, -9, -23, 46, -36, -12, 18, -42, -10, 6, -14, -16, -72, -32, -6, -33, -86, -3, 6, 1, -19, -24, 31, -10, -7, 15, -4, 5, -81, -15, -22, 5, -69, -42, 5, 10, -23, 1, 14, -5, 4, -8, -4, 19, -50, 23, -12, -83, -60, -1, -13, -14, -22, -22, 18, 17, 2, -22, -38, -7, -49, 20, 3, -21, -1, -59, -9, -12, -8, -8, 3, -14, 13, 9, 1, -31, -25, 
  -40, -49, 30, -5, -24, 37, -45, -52, 15, -10, 14, 11, 12, 39, -24, 10, -90, -31, 3, -26, -19, 7, -34, -30, 14, -3, 11, 4, -29, 2, -43, 6, -8, -26, -15, -2, 16, -14, 12, -46, -10, 11, 5, 1, -25, 7, -7, -10, 14, 6, 35, -19, 4, -2, -6, -19, -12, 17, 39, 26, 27, 7, 20, -31, 26, -12, 7, -48, 20, 0, -5, -15, -27, 10, 15, 30, 5, 16, 20, -75, 37, -28, -42, -73, 36, -38, 21, 25, -17, 6, 12, 28, 6, 31, 40, -59, 14, -10, -28, -50, 16, -33, 23, 5, -38, 33, -45, -16, 5, -2, 1, -63, 20, 15, -23, -32, 4, -22, -31, -3, -21, -1, 23, 53, 1, -3, 15, -60, 17, -2, -27, -44, -1, -22, -7, -10, -38, 10, -50, -30, 21, -26, 28, -52, 12, 17, -16, -22, 27, 4, 8, -12, -35, 15, -25, -27, -28, 11, 28, -52, 24, 5, -12, -17, -4, 37, 0, -4, -27, 11, -15, -10, -12, 32, 17, -47, 32, 21, -14, -1, 14, 23, -18, 8, -23, -18, -49, 19, -22, 2, 18, -54, 9, -1, 4, -9, 20, 24, -24, 16, 5, 0, -37, 32, -40, 27, 29, -50, 7, 9, -5, -10, -3, 44, -28, -13, 12, -14, 38, 14, -41, -8, 16, -83, 40, -7, 1, -13, -4, 51, -16, -21, -46, 11, -14, -3, -5, 4, 11, -32, 6, -10, 14, 1, 31, 34, -20, 14, 7, 43, 5, 8, 9, -2, 24, -27, -7, -23, -5, 9, -23, 21, 15, -26, 33, -40, 31, 42, 14, 26, 24, -28, -12, 17, 19, -21, -66, 23, 13, -15, 20, 24, 22, 8, -17, -20, -9, -39, -53, 25, -2, -17, -37, 7, 11, -17, 8, 29, 6, 31, -9, -1, -5, -27, 
  -3, -43, -39, -38, 7, 26, 23, -7, 8, -9, -53, -18, -8, -6, 3, -1, -11, -42, -12, -53, 28, 2, 36, -10, -10, 63, -22, 8, -36, -5, 1, -12, -21, -53, -16, -45, 40, 11, 0, -6, -39, 52, -68, -23, -10, 37, -21, -21, -27, -38, -20, -80, 36, -6, 15, -7, 10, 30, -76, -30, -4, 26, -7, -42, -44, -66, -61, -86, 18, -14, 31, -1, -12, 17, -40, -23, 5, 19, -54, -77, -19, -28, -38, -67, 22, -9, 1, 30, -55, 46, -5, -56, 11, -6, -81, -53, -10, 12, -21, 6, 7, 1, 8, 16, -44, 22, -80, -30, -23, -19, -70, -3, -21, -9, 1, -1, 10, -4, -6, 24, 6, 0, -49, -31, 7, 12, -60, 17, -38, -17, 13, 24, -15, 31, -2, -26, -3, 1, 24, -40, 22, -2, -33, 8, -27, 17, 3, 25, -15, 7, -12, -18, 7, -5, 10, -34, -4, -14, -58, -3, -44, 25, 7, 19, -24, -25, 23, 5, 7, -4, -52, -39, -10, -51, -59, 8, -28, -8, 11, 40, -51, -63, -15, -11, 2, 11, -6, -34, -19, -62, -33, 0, -15, -31, 17, 21, -127, -42, -89, -6, 22, 2, -13, 4, -65, -45, -8, 10, -20, -12, 34, 24, -83, -46, -57, -20, 18, -17, -11, 38, -7, -89, -11, 17, -23, -3, 32, 34, -75, -38, -3, -22, 24, -16, -51, 11, -54, -78, -27, 9, -25, -19, 26, 31, -37, -17, -46, -25, 5, -60, -51, 9, -42, -59, -21, 35, 22, 25, 19, 23, -16, -1, -19, 14, -19, -27, -15, -47, -48, -31, -22, 40, 1, 7, 31, 43, 19, -14, -6, 24, -16, -5, -50, -25, -16, -52, -22, 18, -26, -22, 32, 28, -1, -29, -30, -14, -7, 14, 22, -29, -43, -1, -24, -23, 
  -23, 13, 25, 19, 16, 23, -23, -8, -40, 9, 8, -15, -7, -40, -31, 15, -27, -2, 19, 30, 18, 26, -2, -22, -11, 7, -50, -28, -10, 26, -20, 21, -13, 21, 11, 9, 3, 24, -24, 18, 18, 16, -51, -24, -8, 18, -26, -19, -14, 3, -1, 18, 26, 31, -38, 15, 10, 16, -19, -21, -1, -60, -19, 7, -1, 23, 28, 36, 41, 19, -46, 29, -14, 32, -30, -26, -17, -42, -12, -37, -10, -37, -15, 1, 0, 31, -36, -3, -13, 46, -71, -7, 19, -15, 3, -73, 29, 17, 14, 12, -10, 54, -41, 11, -3, -49, -44, 25, -24, -3, 10, -47, 15, 22, 9, 16, 8, 55, -4, 25, -10, -13, -32, -9, -15, -51, 0, -8, 17, -3, 11, -7, 32, 56, -20, 15, -5, 28, -4, 23, -1, -43, -21, -31, -20, 15, -1, 15, 18, 40, -33, 8, -24, 28, 14, 6, -14, -21, -10, -4, 3, 15, 8, 6, 17, 35, -26, 22, 11, 13, -24, -2, 8, -54, 17, -18, -6, -7, -49, -13, 9, 33, -20, 27, 15, 16, 5, -1, 16, -19, 1, -84, 6, 10, -13, -12, 1, 33, -6, -2, -8, 9, 10, -21, 44, 13, 4, -18, 14, 5, -5, 5, 19, 45, -9, 39, 29, -1, 17, 20, -12, -15, -2, -23, 16, 30, -9, 6, 16, 20, -49, 31, 5, -3, 27, 20, -14, -8, 7, -54, -6, 28, -5, -31, 8, 32, -30, 16, -27, -7, 24, -34, 10, -43, 29, -28, 3, 31, 8, 2, 31, 27, -22, 13, -21, 25, 6, -14, 27, 10, 13, 39, -10, 17, -6, 1, -5, 16, 37, 5, -7, 37, -46, -31, 30, -13, 13, -14, -10, 11, 14, 34, 15, 7, -7, 9, -18, 17, -35, 9, 38, 18, 10, 16, 
};
const TfArray<2, int> tensor_dimension7 = { 2, { 11,304 } };
const TfArray<1, float> quant7_scale = { 1, { 0.0070074941031634808, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data8[16] = { -1103, -2141, -2123, -1331, 912, 68, -854, 448, -1594, -1126, -349, 305, -1442, -1518, -1703, -520, };
const TfArray<1, int> tensor_dimension8 = { 1, { 16 } };
const TfArray<16, float> quant8_scale = { 16, { 0.00015607147361151874, 0.00020395059254951775, 0.00013005168875679374, 0.00022477144375443459, 0.00023251204402185977, 0.00026072331820614636, 0.00017496546206530184, 0.00015165124204941094, 0.00018471336807124317, 0.00019643739506136626, 0.00020981559646315873, 0.00015717113274149597, 0.00012714449258055538, 0.00015272287419065833, 0.00020544747530948371, 0.00022329766943585128, } };
const TfArray<16, int> quant8_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[16*1*3*8] = { 
  /* [0][0][][] */ -54,-11,0,65,-37,-58,61,-57, -37,-7,-22,-36,-66,-27,73,-73, -13,24,-46,-76,-54,-28,127,-59, 
  /* [1][0][][] */ -127,43,-39,39,-77,-77,-55,-30, -55,-40,-57,-32,41,-71,37,35, 37,-76,1,-108,33,-1,65,-7, 
  /* [2][0][][] */ -18,-12,-29,-73,24,-54,15,61, 103,-15,36,-24,74,-119,33,87, -69,62,6,-29,13,-127,24,-10, 
  /* [3][0][][] */ 38,-49,-20,-62,56,-105,-22,44, 9,-68,-31,2,-7,-127,-3,-8, -22,-39,-48,-44,74,-63,69,54, 
  /* [4][0][][] */ -40,4,-28,-47,-108,-33,2,-23, -13,27,10,-73,-83,57,2,-17, 44,41,4,-127,-36,59,17,-13, 
  /* [5][0][][] */ -41,63,-7,-16,-58,-51,-103,16, -61,7,-25,-23,-23,-31,-127,-18, -66,95,7,-20,-36,13,-63,-1, 
  /* [6][0][][] */ 118,26,5,25,-38,-24,-127,-17, 44,-56,2,12,-73,7,-76,-47, -21,-50,-22,82,-66,57,-43,-51, 
  /* [7][0][][] */ -115,47,-61,-20,-82,53,52,-91, -127,38,-94,0,27,-10,-59,-34, -112,37,-127,-94,71,17,118,-28, 
  /* [8][0][][] */ 16,-86,127,8,51,-65,-46,-17, -10,-90,-40,10,74,-61,-60,14, -20,-92,115,37,5,-49,-83,5, 
  /* [9][0][][] */ -41,-26,-52,-13,-73,88,-10,-15, -21,-102,-110,-19,-19,13,-24,-4, -3,-112,-127,-15,-14,87,-30,68, 
  /* [10][0][][] */ -95,-28,-79,21,-5,5,-8,-37, -81,-15,-61,10,-45,-52,-41,-1, -32,-5,-75,41,-35,-97,-10,127, 
  /* [11][0][][] */ -69,-17,-19,78,18,-73,-91,17, -125,-30,-31,43,29,-127,-41,88, -99,-1,13,80,-69,-87,-41,-35, 
  /* [12][0][][] */ -86,2,-114,104,-127,-28,-22,-108, 45,-35,-55,-50,-29,85,-109,-64, 112,-15,15,6,15,-39,-80,74, 
  /* [13][0][][] */ 93,-14,11,-41,-127,117,-76,-30, 12,8,-9,-34,-122,-31,-99,-30, 0,57,122,-63,-40,-82,-9,-1, 
  /* [14][0][][] */ 18,-77,55,-41,-30,-16,83,-73, 0,-30,117,-40,-50,-9,26,-110, 3,-94,76,-55,-16,6,9,-127, 
  /* [15][0][][] */ 76,38,-32,-87,0,-65,-48,54, 41,-2,-37,-117,27,-47,-33,24, 43,3,-47,-127,-18,16,-48,25, 
};
const TfArray<4, int> tensor_dimension9 = { 4, { 16,1,3,8 } };
const TfArray<16, float> quant9_scale = { 16, { 0.0034639874938875437, 0.0045266589149832726, 0.0028864815831184387, 0.004988775122910738, 0.0051605766639113426, 0.0057867225259542465, 0.0038833373691886663, 0.0033658810425549746, 0.0040996908210217953, 0.0043599042110145092, 0.0046568317338824272, 0.0034883941989392042, 0.0028219567611813545, 0.003389665624126792, 0.0045598819851875305, 0.0049560647457838058, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data10[8] = { -2713, -903, -2169, -2050, -3115, -1610, -3080, -1776, };
const TfArray<1, int> tensor_dimension10 = { 1, { 8 } };
const TfArray<8, float> quant10_scale = { 8, { 0.00023661051818635315, 0.00022780531435273588, 0.00025233399355784059, 0.00015080647426657379, 0.0001800012105377391, 0.0002322126820217818, 0.00022269392502494156, 0.00022750890639144927, } };
const TfArray<8, int> quant10_zero = { 8, { 0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data11[8*1*3*13] = { 
  /* [0][0][][] */ 0,-19,-16,73,-112,-48,35,18,-47,4,-3,21,18, -4,-58,-67,58,-127,-34,12,42,-45,11,-14,6,-25, 15,-33,-67,60,-93,-25,41,32,-1,1,17,-26,75, 
  /* [1][0][][] */ -105,40,24,43,-77,-33,1,86,-45,22,-32,0,29, -127,76,23,1,-42,-6,23,79,-37,63,7,30,23, -96,28,24,-5,-58,-78,-28,50,-5,15,-62,0,54, 
  /* [2][0][][] */ 16,11,15,-15,-111,77,-13,-23,45,-7,12,6,-10, -52,-17,59,-21,-115,127,-17,13,28,2,16,1,-41, -27,-28,46,-29,-118,116,-56,12,51,-4,63,-28,4, 
  /* [3][0][][] */ -79,-55,14,-11,113,23,100,-84,102,-110,21,-127,13, -9,-117,-20,63,69,76,71,-83,115,-52,52,20,10, 7,-92,50,38,112,92,107,-92,-5,-27,58,7,-73, 
  /* [4][0][][] */ 45,-13,76,127,-61,-32,-83,-26,-4,42,30,-26,-70, 66,19,83,63,-51,0,1,-81,-55,16,67,-49,12, 51,-40,112,30,-77,32,-38,-57,-14,32,-12,-47,-77, 
  /* [5][0][][] */ 80,46,-107,-70,77,31,14,27,-21,5,-57,2,-4, 103,-28,-127,-90,36,3,42,-18,-42,-5,-57,25,28, 57,29,-111,33,25,33,33,6,-52,-11,-27,-34,53, 
  /* [6][0][][] */ 40,127,34,-32,-49,-15,32,-57,-83,-70,45,42,-42, 79,96,33,-58,-56,5,18,-37,-47,12,50,14,-46, 60,74,37,-40,-38,-21,6,-69,-55,85,-7,20,-62, 
  /* [7][0][][] */ 16,48,63,120,10,-57,-3,17,-25,-44,56,2,38, -14,-6,-6,93,-14,-52,26,15,-7,-40,43,-23,9, 12,36,27,127,-28,-84,3,39,-29,-29,48,0,-1, 
};
const TfArray<4, int> tensor_dimension11 = { 4, { 8,1,3,13 } };
const TfArray<8, float> quant11_scale = { 8, { 0.0045323176309466362, 0.0043636523187160492, 0.0048335036262869835, 0.0028887256048619747, 0.0034479559399187565, 0.004448076244443655, 0.0042657428421080112, 0.0043579745106399059, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const TfArray<4, int> tensor_dimension12 = { 4, { 1,1,75,13 } };
const TfArray<4, int> tensor_dimension13 = { 4, { 1,1,75,8 } };
const TfArray<1, float> quant13_scale = { 1, { 0.045055437833070755, } };
const TfArray<1, int> quant13_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&quant13_zero, 0 };
const TfArray<4, int> tensor_dimension14 = { 4, { 1,75,1,8 } };
const TfArray<4, int> tensor_dimension15 = { 4, { 1,38,1,8 } };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,38,8 } };
const TfArray<4, int> tensor_dimension17 = { 4, { 1,1,38,16 } };
const TfArray<1, float> quant17_scale = { 1, { 0.048480335623025894, } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&g0::quant13_zero, 0 };
const TfArray<4, int> tensor_dimension18 = { 4, { 1,38,1,16 } };
const TfArray<4, int> tensor_dimension19 = { 4, { 1,19,1,16 } };
const TfArray<2, int> tensor_dimension20 = { 2, { 1,304 } };
const TfArray<2, int> tensor_dimension21 = { 2, { 1,11 } };
const TfArray<1, float> quant21_scale = { 1, { 0.1630721390247345, } };
const TfArray<1, int> quant21_zero = { 1, { 55 } };
const TfLiteAffineQuantization quant21 = { (TfLiteFloatArray*)&quant21_scale, (TfLiteIntArray*)&quant21_zero, 0 };
const TfArray<1, float> quant22_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant22 = { (TfLiteFloatArray*)&quant22_scale, (TfLiteIntArray*)&g0::quant13_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 12 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 12,11,10 } };
const TfArray<1, int> outputs1 = { 1, { 13 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 13,2 } };
const TfArray<1, int> outputs2 = { 1, { 14 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 14 } };
const TfArray<1, int> outputs3 = { 1, { 15 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 15,3 } };
const TfArray<1, int> outputs4 = { 1, { 16 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 16,9,8 } };
const TfArray<1, int> outputs5 = { 1, { 17 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 17,4 } };
const TfArray<1, int> outputs6 = { 1, { 18 } };
const TfLitePoolParams opdata7 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs7 = { 1, { 18 } };
const TfArray<1, int> outputs7 = { 1, { 19 } };
const TfLiteReshapeParams opdata8 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs8 = { 2, { 19,5 } };
const TfArray<1, int> outputs8 = { 1, { 20 } };
const TfLiteFullyConnectedParams opdata9 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs9 = { 3, { 20,7,6 } };
const TfArray<1, int> outputs9 = { 1, { 21 } };
const TfLiteSoftmaxParams opdata10 = { 1 };
const TfArray<1, int> inputs10 = { 1, { 21 } };
const TfArray<1, int> outputs10 = { 1, { 22 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 976), (TfLiteIntArray*)&g0::tensor_dimension0, 975, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 44, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 3344, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 384, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension11, 312, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension12, 975, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 976), (TfLiteIntArray*)&g0::tensor_dimension13, 600, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension14, 600, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 608), (TfLiteIntArray*)&g0::tensor_dimension15, 304, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension16, 304, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 608), (TfLiteIntArray*)&g0::tensor_dimension17, 608, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 608, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 608), (TfLiteIntArray*)&g0::tensor_dimension19, 304, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension20, 304, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 304), (TfLiteIntArray*)&g0::tensor_dimension21, 11, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension21, 11, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 23, };
const size_t tflNodes_subgraph_index[] = {0, 11, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  22, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1106390_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 23;
  for (size_t i = 0; i < 23; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1106390_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1106390_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1106390_3_invoke() {
  for (size_t i = 0; i < 11; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1106390_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
